### ISSUE TITLE
Using existing Private Space on Heroku

### ISSUE THREAD

**Issue by jorgeorpinel** [heroku-examples/terraform-heroku-peered-redshift#3]
I'm not a Terraform expert but I imagine it's a small change to use an existing space instead of creating one?

I tried adding
```
  TF_VAR_heroku_space_name='your-existing-private-space-name' \
```
to .env,
```
variable "heroku_space_name" {}
```
to variables.tf, and changing that value in main.tf line 28:
```
  name         = "${var.heroku_space_name}"
```
but `terraform apply` complains that the space name already exists. (It's trying to create it.)

My question is what to cahange in the .tf files so it doesn't attempt to create a new space but rather uses an existing one. Thanks!

**Comment by mars** [comment]
Hi @jorgeorpinel 😄

Terraform solves this problem with the [`terraform import` command](https://www.terraform.io/docs/import/index.html), which is fully supported by the Heroku provider.
